import { useState, useCallback } from 'react';
import { MapView } from './components/MapView';
import { TimelineBar } from './components/TimelineBar';
import { InfoPanel } from './components/InfoPanel';
import { CategoryFilter } from './components/CategoryFilter';
import { useTimeline } from './hooks/useTimeline';
import type { FeatureProperties, Category } from './types';
import { ALL_CATEGORIES } from './theme/categories';

// Static seed data — generated by scripts/export-geojson.ts
// Replace with API call once the backend is running.
import seedData from './data/seed.geojson';

const geojson = seedData as GeoJSON.FeatureCollection;

export default function App() {
  const timeline = useTimeline();
  const [selectedFeature, setSelectedFeature] = useState<FeatureProperties | null>(null);
  const [activeCategories, setActiveCategories] = useState<Set<Category>>(
    new Set(ALL_CATEGORIES),
  );

  const handleToggleCategory = useCallback((cat: Category) => {
    setActiveCategories((prev) => {
      const next = new Set(prev);
      if (next.has(cat)) {
        next.delete(cat);
      } else {
        next.add(cat);
      }
      return next;
    });
  }, []);

  const handleSelectFeature = useCallback((props: FeatureProperties) => {
    setSelectedFeature(props);
  }, []);

  const handleClosePanel = useCallback(() => {
    setSelectedFeature(null);
  }, []);

  return (
    <div style={{ width: '100vw', height: '100vh', overflow: 'hidden', background: '#1a1a2e' }}>
      <CategoryFilter
        activeCategories={activeCategories}
        onToggle={handleToggleCategory}
      />

      <div style={{ position: 'absolute', inset: '48px 0 56px 0' }}>
        <MapView
          geojson={geojson}
          currentYear={timeline.currentYear}
          activeCategories={activeCategories}
          onSelectFeature={handleSelectFeature}
        />
      </div>

      <InfoPanel
        feature={selectedFeature}
        onClose={handleClosePanel}
      />

      <TimelineBar
        currentYear={timeline.currentYear}
        stepSize={timeline.stepSize}
        stepOptions={timeline.stepOptions}
        isPlaying={timeline.isPlaying}
        playbackSpeed={timeline.playbackSpeed}
        onSeek={timeline.seek}
        onStep={timeline.step}
        onTogglePlay={timeline.togglePlay}
        onSetStepSize={timeline.setStepSize}
        onSetSpeed={timeline.setPlaybackSpeed}
      />
    </div>
  );
}
