import { useState, useCallback, useEffect, useRef } from 'react';
import { checkLogin } from './lib/wikidataApi';
import { fetchOverrides } from './lib/api';
import { MapView } from './components/MapView';
import { TimelineBar } from './components/TimelineBar';
import { InfoPanel } from './components/InfoPanel';
import { CategoryFilter } from './components/CategoryFilter';
import { DataExplorer } from './components/DataExplorer';
import { MajorEventsPanel } from './components/MajorEventsPanel';
import { useTimeline, encodeDate, STEP_YEAR } from './hooks/useTimeline';
import type { FeatureProperties, Category } from './types';
import type { StackInfo, ZoomRequest } from './components/MapView';
import { ALL_CATEGORIES, EVENT_CATEGORIES, POLITY_CATEGORIES } from './theme/categories';

// Static seed data — generated by scripts/export-geojson.ts
// Replace with API call once the backend is running.
import seedData from './data/seed.geojson';

export default function App() {
  const [currentPath, setCurrentPath] = useState(() => window.location.pathname);
  const [geojson, setGeojson] = useState<GeoJSON.FeatureCollection>(seedData as GeoJSON.FeatureCollection);
  const timeline = useTimeline();
  const [selectedFeature, setSelectedFeature] = useState<FeatureProperties | null>(null);
  const [stack, setStack] = useState<StackInfo>({ index: 0, total: 1 });
  const [activeCategories, setActiveCategories] = useState<Set<Category>>(
    new Set(EVENT_CATEGORIES as Category[]),
  );
  const [activePolityCategories, setActivePolityCategories] = useState<Set<Category>>(
    new Set(POLITY_CATEGORIES.filter((c) => c !== 'principality') as Category[]),
  );
  const [zoomRequest, setZoomRequest] = useState<ZoomRequest | null>(null);
  const zoomIdRef = useRef(0);
  const [wikiAuth, setWikiAuth] = useState<string | null>(null);

  // Check for existing Wikipedia session on mount
  useEffect(() => {
    checkLogin().then((username) => setWikiAuth(username));
  }, []);

  // Merge any API-persisted corrections over the static seed.geojson baseline
  useEffect(() => {
    fetchOverrides()
      .then((overrides) => {
        if (overrides.features.length === 0) return;
        setGeojson((base) => {
          const overrideMap = new Map(
            overrides.features.map((f) => [(f.properties as { id: string }).id, f]),
          );
          return {
            ...base,
            features: base.features.map((f) => overrideMap.get((f.properties as { id: string }).id) ?? f),
          };
        });
      })
      .catch(() => {/* API not running — silently fall back to static GeoJSON */});
  }, []);

  useEffect(() => {
    const onPop = () => setCurrentPath(window.location.pathname);
    window.addEventListener('popstate', onPop);
    return () => window.removeEventListener('popstate', onPop);
  }, []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== 'Escape') return;
      const tag = (e.target as HTMLElement)?.tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA') return;
      setSelectedFeature(null);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  const navigate = useCallback((to: string) => {
    window.history.pushState({}, '', to);
    setCurrentPath(to);
  }, []);

  const handleToggleCategory = useCallback((cat: Category) => {
    setActiveCategories((prev) => {
      // All active → solo the clicked one
      if (prev.size === ALL_CATEGORIES.length) {
        return new Set([cat]);
      }
      const next = new Set(prev);
      if (next.has(cat)) {
        next.delete(cat);
        // Last one removed → reset to all
        if (next.size === 0) return new Set(ALL_CATEGORIES);
      } else {
        next.add(cat);
      }
      return next;
    });
  }, []);

  const handleTogglePolityCategory = useCallback((cat: Category) => {
    setActivePolityCategories((prev) => {
      // All active → solo the clicked one
      if (prev.size === POLITY_CATEGORIES.length) {
        return new Set([cat]);
      }
      const next = new Set(prev);
      if (next.has(cat)) {
        next.delete(cat);
        // Last one removed → reset to all polity categories
        if (next.size === 0) return new Set(POLITY_CATEGORIES as Category[]);
      } else {
        next.add(cat);
      }
      return next;
    });
  }, []);

  const handleSelectFeature = useCallback((props: FeatureProperties, stackInfo: StackInfo) => {
    setSelectedFeature(props);
    setStack(stackInfo);
    if (props.yearStart !== null) {
      const isStaticFeature = props.featureType === 'city' || props.featureType === 'region'
        || props.featureType === 'country' || props.featureType === 'polity';
      if (!isStaticFeature) {
        const featureDateInt = encodeDate(props.yearStart, props.monthStart ?? 1, props.dayStart ?? 1);
        const cur = timeline.currentDateInt;
        const activeNow = props.yearEnd != null
          ? cur >= featureDateInt && cur <= encodeDate(props.yearEnd, props.monthEnd ?? 12, props.dayEnd ?? 31)
          : cur === featureDateInt;
        if (!activeNow) timeline.seek(featureDateInt);
      }
    }
  }, [timeline]);

  const handleClosePanel = useCallback(() => {
    setSelectedFeature(null);
  }, []);

  const handleFeatureUpdated = useCallback((updates: Partial<FeatureProperties> & { _coords?: [number, number] }) => {
    setSelectedFeature((prev) => {
      if (!prev) return prev;
      const { _coords, ...propsOnly } = updates as Partial<FeatureProperties> & { _coords?: [number, number] };
      const updated = { ...prev, ...propsOnly };
      setGeojson((gj) => ({
        ...gj,
        features: gj.features.map((f) => {
          if ((f.properties as FeatureProperties).id !== prev.id) return f;
          const patched = { ...f, properties: updated };
          if (_coords) return { ...patched, geometry: { type: 'Point' as const, coordinates: _coords } };
          return patched;
        }),
      }));
      return updated;
    });
  }, []);

  const handleNavigateToFeature = useCallback((feature: FeatureProperties) => {
    if (feature.yearStart !== null) {
      const featureStart = encodeDate(feature.yearStart, feature.monthStart ?? 1, feature.dayStart ?? 1);
      const featureEnd   = feature.yearEnd != null
        ? encodeDate(feature.yearEnd, feature.monthEnd ?? 12, feature.dayEnd ?? 31)
        : encodeDate(feature.yearStart, 12, 31);
      const cur = timeline.currentDateInt;
      // Match MapView's visibility window: event is visible while
      //   featureStart <= cur+stepSize-1  AND  cur <= featureEnd + FADE_INT (3 years)
      // Only seek if the event is completely outside that window.
      const effectiveNow = cur + timeline.stepSize - 1;
      const isVisible = featureStart <= effectiveNow && cur <= featureEnd + 3 * STEP_YEAR;
      if (!isVisible) timeline.seek(featureStart);
    }
    // Ensure all of the feature's categories are visible
    if (feature.featureType === 'polity') {
      setActivePolityCategories((prev) => {
        const missing = feature.categories.filter((c) => !prev.has(c as Category));
        if (missing.length === 0) return prev;
        const next = new Set(prev);
        missing.forEach((c) => next.add(c as Category));
        return next;
      });
    } else {
      setActiveCategories((prev) => {
        const missing = feature.categories.filter((c) => !prev.has(c as Category));
        if (missing.length === 0) return prev;
        const next = new Set(prev);
        missing.forEach((c) => next.add(c as Category));
        return next;
      });
    }
    navigate('/');
    setZoomRequest({ feature, id: ++zoomIdRef.current });
  }, [timeline, navigate]);

  const handleDataExplorerFeatureUpdated = useCallback((featureId: string, updates: Partial<FeatureProperties>) => {
    setGeojson((gj) => ({
      ...gj,
      features: gj.features.map((f) =>
        (f.properties as FeatureProperties).id === featureId
          ? { ...f, properties: { ...f.properties, ...updates } }
          : f,
      ),
    }));
  }, []);

  if (currentPath === '/data') {
    return (
      <DataExplorer
        geojson={geojson}
        onBackToMap={() => navigate('/')}
        onNavigateToFeature={handleNavigateToFeature}
        wikiAuth={wikiAuth}
        onAuth={setWikiAuth}
        onFeatureUpdated={handleDataExplorerFeatureUpdated}
      />
    );
  }

  return (
    <div style={{ width: '100vw', height: '100vh', overflow: 'hidden', background: '#f8f9fa' }}>
      <CategoryFilter
        activeCategories={activeCategories}
        onToggle={handleToggleCategory}
        activePolityCategories={activePolityCategories}
        onTogglePolity={handleTogglePolityCategory}
        onOpenData={() => navigate('/data')}
      />

      <div style={{ position: 'absolute', inset: '89px 0 104px 0' }}>
        <MapView
          geojson={geojson}
          currentDateInt={timeline.currentDateInt}
          stepSize={timeline.stepSize}
          activeCategories={activeCategories}
          activePolityCategories={activePolityCategories}
          onSelectFeature={handleSelectFeature}
          zoomRequest={zoomRequest}
        />
      </div>

      <InfoPanel
        feature={selectedFeature}
        stack={stack}
        onClose={handleClosePanel}
        geojson={geojson}
        onNavigateToFeature={handleNavigateToFeature}
        wikiAuth={wikiAuth}
        onAuth={setWikiAuth}
        onFeatureUpdated={handleFeatureUpdated}
      />

      <MajorEventsPanel
        geojson={geojson}
        currentDateInt={timeline.currentDateInt}
        stepSize={timeline.stepSize}
        onNavigateToFeature={handleNavigateToFeature}
      />

      <TimelineBar
        currentDateInt={timeline.currentDateInt}
        stepSize={timeline.stepSize}
        stepOptions={timeline.stepOptions}
        isPlaying={timeline.isPlaying}
        playbackSpeed={timeline.playbackSpeed}
        onSeek={timeline.seek}
        onStep={timeline.step}
        onTogglePlay={timeline.togglePlay}
        onSetStepSize={timeline.setStepSize}
        onSetSpeed={timeline.setPlaybackSpeed}
      />
    </div>
  );
}
